### ISSUE TITLE
image list can sort by create date?

### ISSUE THREAD

**Issue by Jrohy** [Joxit/docker-registry-ui#109]
wish add sort by create date, default new image in head list

**Comment by Joxit** [comment]
Hello,

This feature can't work because the "last update" information is not provided by the registry server.
In order to have this information, we must query all tags one by one for all images get the newer and then sort images... :disappointed:

It will be the same thing for tags, we can't sort them by date, because we can't query all tags one by one when the pagination is activated (more than 100 tags for an image).
