### ISSUE TITLE
Multi-delete tags UI not working?

### ISSUE THREAD

**Issue by cr1st1p** [Joxit/docker-registry-ui#119]
Hi, I use this docker registry UI and I have an issue...

## Bug description

I want to bulk delete some image tags. It seems that I can not - buttons disappear

## How to Reproduce

For UI bug, steps to reproduce the behavior:
1. Show an image with multiple tags
2. As per tooltip, ALT-Click on the top-right delete checkbox (to 'delete all')
  First bug: nothing happens. Chromium, Linux
3.Simple click on the top-right delete checkbox. Checkbox transforms into a minus '-' sign. Ok.
  **But** the trash icon disappears. It should not.
4. Select a few tags.
5. Try delete them. Wait - you can't, there's no button to click on (the trash can one who disappeared at step 3)

Additionally, another bug :
1,4 - the same
  Immediately after selecting an item, the 'minus' sign disappears.
  I don't think it should, you should be able to revert to the single-item-delete flow. i.e. the minus button to remain, and if you select it, change back the ui to a checkbox + individual trashcan links
  Even if you clear all selections, the minus sign does not appear back.

## System information
 
- OS: Manjaroo (Arch based) Linux

- Browser:
    - Name:  Chromium
    - Version: 79.0
- Docker registry UI:
    - Version: 1.4.4
    - Interface variant: ?
    - Server: docker
    - Docker version: [e.g. 19.03]
    - OS/Arch: [e.g. linux/amd64]
    - Tools: Kubernetes

**Comment by Joxit** [comment]
Hi, sorry, this bug was introduced in 1.4.3 :sweat_smile: 

Should be OK with 1.4.5, pull the image when it's ready

**Comment by Joxit** [comment]
The ALT+Click is available only when the minus icon is present. But you are right, it makes sense to have it all the time

**Comment by knipknap** [comment]
Does this actually work? On Linux, Alt+Click means "move the Window", and since OP is using Linux, I don't see how this could work.
Is there another shortcut for multi-selection?

**Comment by Joxit** [comment]
Hum... Yes this actually work... I'm using Chrome on Debian and it works like a charm... The move window is when you ALT + drag and drop, this is only a ALT + click...
And it seems to be disabled anyway on browser since it's a common usage to use shortcuts with ALT, CTRL etc

Try it and see.

**Comment by knipknap** [comment]
I tried, it doesn't work on mine ;-)

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

I'm using xorg.

**Comment by Joxit** [comment]
When I added this feature I was on Xorg IIRC, so this may be caused by ubuntu or Unity :shrug:. It seems that Linux Mint had the same [default shortcut and issue](https://www.reddit.com/r/linuxmint/comments/cf4wfa/altclick_does_not_work_in_chromium_or_firefox/) 

Anyway, I'm working on a SHIFT + click feature as asked in #258 but you will need to wait [v2.4.0](https://github.com/Joxit/docker-registry-ui/milestone/5) (87% complete)

Stay tuned !

**Comment by knipknap** [comment]
Hmmm, wouldn't it be more intuitive to adopt the IMO more common convention, where the checkbox above means "select all/nothing", and when something is selected a delete button appears next to it?
I think the alt-select is also pretty hidden which is why I Googled and found this issue ;-)

**Comment by Joxit** [comment]
I do not like the delete button next to the checkbox, this may be dangerous (miss click) and its not really nice 😅

The icons will no longer be aligned and this creates a dissonance.
That's why I chose a shortcut (alt + click) and I like the idea of shift + click (even if it's not mobile friendly) since it's often use even with file managers 😊
