### ISSUE TITLE
Trying to delete item by item "too fast" shows an error

### ISSUE THREAD

**Issue by cr1st1p** [Joxit/docker-registry-ui#120]
Hi, I use this docker registry UI and I have an issue...

## Bug description

Since for now multi-select + delete does not work for me, I try to delete items one-by one.
But if I'm in a hurry and click "too fast", I get an error.

## How to Reproduce

For UI bug, steps to reproduce the behavior:
1. Go to a docker image  and look at all the tags
2. Click on first item's delete link (trashcan)
3. Immediately after the new list appears, with that item deleted, click on the next item's (which is now row 1) delete link. I get an error 
```
Access on registry response was blocked. Try adding the header `Access-Control-Expose-Headers: Docker-Content-Digest` to your proxy or registry: https://docs.docker.com/registry/configuration/#http
```

## Expected behavior

Either I should not be able to click on the delete icon until things 'settle' up, or that 2nd item get deleted.

If I leave ~1 second and click the icon, on that 2nd item, it works.

## System information
 
- OS: Manjaroo (Arch based) Linux

- Browser:
    - Name:  Chromium
    - Version: 79.0
- Docker registry UI:
    - Version: 1.4.4
    - Interface variant: ?
    - Server: docker

    - Docker version: [e.g. 19.03]
    - OS/Arch: [e.g. linux/amd64]
    - Tools: Kubernetes

**Comment by Joxit** [comment]
Hi again,

Ok, this one is because the component is not yet loaded, we get only the tag and not other information (digest, size, etc). If the digest is missing, I assume that something is wrong and warn with an error. But here it's because it needs more time to do the second request...

https://github.com/Joxit/docker-registry-ui/blob/2e915a82b185b342817ef94aaf7b44c77fabdb33/src/tags/remove-image.tag#L36-L40

So disable the button until the component is ok ?

I can easily reproduce this behaviour with a very slow internet connection.

**Comment by cr1st1p** [comment]
Maybe have from the beginning a small loading icon/gif, and when things gets loaded for that record, replace with the trashcan icon? Of course, we're talking about display/hide of the icons.

**Comment by Joxit** [comment]
Yes, or I display the icon iff the digest is present, I will try this tonight

**Comment by Joxit** [comment]
Should be done in 1.4.6. 
New message when you click on the trash with different color when the digest is not present.
I improved the Alt+Click too. Now you can Alt+click the trash to unselect all and Alt+click on the unchecked checkbox to select all :smile:
