### ISSUE TITLE
when delete one tag, all tags with same SHA deleted

### ISSUE THREAD

**Issue by fanlix** [Joxit/docker-registry-ui#157]
```
docker tag image-abc image-abc:v1.0
docker tag image-abc image-abc:latest
docker push ...
```

on register-ui, delete image-abc:<kbd>v1.0</kbd>.   
then image-abc:<kbd>latest</kbd> also deleted.

Sry to report this as a bug,
I dont know whether this is a bug or behavior,
and which one to blame to : docker/registry/registry-ui ?

**Comment by Joxit** [comment]
Hi

This is sadly a docker registry API limitation, there is only one way to [delete images with tag](https://docs.docker.com/registry/spec/api/#deleting-an-image), it's by its `name` and its `manifest` (it's a sha of the content).

See #96 

I will not close this issue because this was not clear enough, I should add a question in the FAQ and improve the delete feature ( https://github.com/Joxit/docker-registry-ui/issues/96#issuecomment-524301435 or https://github.com/Joxit/docker-registry-ui/issues/96#issuecomment-524755683 ? :shrug:).

**Comment by fanlix** [comment]
gotcha, it's registry problem: no api to delete tags.

**Comment by Joxit** [comment]
Close the issue due to inactivity
