### ISSUE TITLE
Need confirmation dialog box when i click on delete image icon. 

### ISSUE THREAD

**Issue by vidhya199** [Joxit/docker-registry-ui#166]
HI,

i am using your UI but i need some changes in that . 
when i want to delete image or tag its directly deleted without any confirmation. yes /no , when i click on yes then its should get deleted. 

on main page its show count of images its not images count its should be repository count.

**Comment by Joxit** [comment]
Hi,

What do you mean by "on main page its show count of images its not images count its should be repository count." ?

**Comment by joshaw** [comment]
I agree, a confirmation dialog when deleting images would be helpful.

I think @vidhya199 is referring to this label:
![image](https://user-images.githubusercontent.com/3018066/108061270-f92aef80-704f-11eb-87c5-2f93674f3819.png)
Instead of "images", I think they're suggesting it say "21 repositories". Since each entry on that page is a repository that itself contains several images, each of which has it's own tag (not sure which I would choose, just explaining what I think vidhya199 is saying!)
