### ISSUE TITLE
Disable trashbin button when read-only

### ISSUE THREAD

**Issue by jorgefm** [Joxit/docker-registry-ui#181]
Is it possible to disable the trashbin button when you are logged as a read-only user?
I've followed the examples/read-only-auth. With the DELETE_IMAGES=true the web UI shows the trashbin button and when is pressed from a read-only user, the loging window is displayed again. If a read-write user is logged ok the delete operation is done ok, but if I user a read-only user again an error is returned and the web UI is not working again because no repository content is displayed.
Is it possible to disable the trashbin button when a read-only user is logged?
Thanks

**Comment by Joxit** [comment]
Hi, thank you for your issue.

No, it's not possible to hide this trash icon only for read only users. The UI can't know user rights at login.

But you said that the UI is not working after a delete failure? What version do you use?

**Comment by jorgefm** [comment]
I'm using v1.5.4

**Comment by Joxit** [comment]
Okay, I'm working on 2.0.0 available with the image `joxit/docker-registry-ui:main`, can you tell me if the issue is still present ?

The migration guide is [here](https://github.com/Joxit/docker-registry-ui/wiki/Migrating-from-1.x-to-2.x)

The major change is the use of `SINGLE_REGISTRY` instead of the `static` tag.

**Comment by jorgefm** [comment]
No, it's not working...
I'm running the new version with

docker run -d --net registry-ui-net -p 8080:80 --restart=always \
 -e SINGLE_REGISTRY=true -e DELETE_IMAGES=true -e REGISTRY_TITLE="Private Docker Registry" \
 -v /home/admin/registry/nginx.conf:/etc/nginx/conf.d/default.conf \
 -v /home/admin/registry/read-write.htpasswd:/etc/nginx/auth/read-write.htpasswd:ro \
 -v /home/admin/registry/read-only.htpasswd:/etc/nginx/auth/read-only.htpasswd \
 joxit/docker-registry-ui:main

I login with a read-only user. The I go to a tag and I try to remove it. The UI ask for a new user. I entry the read-only again, press OK and the login window is displayed again. After several times, I press CANCEL instead, and when the UI is displayed back again no info is shown... I guess that is an expected behavior because no user is logged.

**Comment by Joxit** [comment]
Oh, I understand now, this is because of the [Basic Access Authentication Protocol](https://en.wikipedia.org/wiki/Basic_access_authentication#Protocol). In order to trigger the browser auth dialog, the server must send a `401 Unauthorized` HTTP response with the header `WWW-Authenticate: Basic realm="User Visible Realm"`. When you are logged in, the browser will save your credentials and will use them for all requests on the same endpoint. This is what is happening when you want to access to the catalog for example.

But when you want to delete an image with a read-only user, the server will also return a `401 Unauthorized` HTTP response with the header... And this will trigger again the Basic Access Authentication Protocol....

IDK how I can fix this... This should be done in server side... :thinking:

**Comment by jorgefm** [comment]
Ok, I undestand... I can live with it :)
And is it possible to get a logout option?

**Comment by Joxit** [comment]
Sorry, I auto-closed this issue by accident... I was targeting 191 :sweat_smile: 

I can't add a logout option because all the auth process is done by the browser.

In fact it's possible with a fake route on the registry that returns always 401... but not really elegant
