### ISSUE TITLE
Display total size of image

### ISSUE THREAD

**Issue by andrii29** [Joxit/docker-registry-ui#195]
Hello,
please add total size of image.

We can see size of image tags, but can not see total size of image (exclude layer mounts). It would be very useful to get this data in image list

For example
```
prod/ (17G)
  prod/image1 (1.25G)
  prod/image2 (223M)
  ...
stage/ (2.3G)
  stage/image1 (1.44G)
  stage/image2 (444M)
  ...
```

**Comment by Joxit** [comment]
Hello, thank you for using my project and this feature request.

I'm sorry but this will not be possible for three reasons:
1. The access of the size of an image/tag needs too many requests and will just break the UI or worst, the registry server. I need for each images, get it's tag list and the for each tags get its manifest (which contains the size). 
2. Someone with 10 images and each images with 10 tags will generate 100 + 10 requests. Our browsers are limited to 6 requests simultaneously to one endpoint... This can take times and reduce the User eXperience
3. This will not be an accurate size, we often use tag aliases (e.g `latest`), that means you will see 1.44G for 3 480Mo images but in fact this should be 960Mo because of your alias.
