### ISSUE TITLE
push release tags to docker hub

### ISSUE THREAD

**Issue by Raboo** [Joxit/docker-registry-ui#202]
Hi,

Could you please push a docker hub tag for each release with exact version starting from 2.0.8?
Currently docker hub has 2.0.
I am currently running 2.0 tag but it's not clear which 2.0.x release I am running and also makes it harder to pin a specific releases.

Let me know if you need help with the docker hub automated build regex.

Thanks

**Comment by Joxit** [comment]
Hi,

Thank you for using my project :smile: 
The version 2.0 on docker is always the latest `2.0.x` version, in order to update your image, you just need to do a `docker pull joxit/docker-registry-ui:2.0` to get all fixes.

Every minor versions (`2.x`) add new features/options/ui changes.
Every major versions add [breaking changes](https://github.com/Joxit/docker-registry-ui/wiki/Migrating-from-1.x-to-2.x)

I prefer not to introduce the patch versions on docker hub for several reasons:
1. From my point of view, patch tags are ephemeral images.
2. This will drastically increase the number of available images.
3. I'm using a Free plan on docker hub and last year Docker announced that they will introduce [retention policy on inactive images](https://www.docker.com/blog/scaling-dockers-business-to-serve-millions-more-developers-storage/). If they do that, it could break some integrations (e.g deleted tag in your configuration).
4. They wrote that the 15PB of images stored in Docker Hub, over 10PB of these images were inactive, so I also prefer to reduce the consumption of my projects.

I'm not using Docker Hub Automated Build anymore, now I'm using Github Actions because they are supporting multi platform images :wink:

**Comment by Raboo** [comment]
Well in my use case, running `joxit/docker-registry-ui:2.0` in Kubernetes, there is no proper way to upgrade. I can delete the pod and hope it gets rescheduled on a node that doesn't have the `joxit/docker-registry-ui:2.0` downloaded already. But there is really no sure way to ensure I'm running the latest version.

I suspect that when using different container image caching solutions it might break as well.

Also have you considered the possibility that you one day might publish a broken `joxit/docker-registry-ui:2.0` image. Then there will no way to download a working image until you've pushed a fixed version.

Also you can look at the retention policy as a cleanup tool. When you have old releases in docker hub that aren't downloaded any more, they get cleaned up automatically for you (sure 6 months is a bit short).
And I'm not saying you shouldn't push the 2.0 tag, just that you add an extra tag for every release.
And if you have problem with the retention policy deleting the 2.0 tag then you can simply setup a cron based Github action that pushes the 2.0 tag every month.

Also a little bit off topic to this conversation, why do you need both Alpine and Debian images? A big benefit of docker images is to abstract away the OS. I would simply just keep the Alpine (smaller in footprint).

**Comment by Joxit** [comment]
Hum, ok I see. Why don't you use `imagePullPolicy: Always` ?

I'm not afraid that tag 2.0 will be deleted, because this tag is also an alias to `latest` and would be an alias for the latest 2.0.x as well. That means pulling 2.0.x will count for 2.0 and latest (thank you Github Actions).
Only old 2.0.x will be stale images.

Anyway, you certainly have a point here with broken versions, sometimes nginx image on linux/arm do not work and can't be fixed by me (see #186)... :confused: 

A few years ago someone had an issue with `nginx:alpine` not starting on his computer (it was maybe a raspberry pi or something like that)... Debian fixed his issue so... Here we are 4 years later :sweat_smile: And this tag is still in use !

**Comment by Raboo** [comment]
Hmm, I didn't think of that.
Maybe that will work, I don't know how the mechanics of `imagePullPolicy: Always` works, perhaps it will always pull the latest image.

I will try it and let you know, but I won't know if it works until you release a new version.

**Comment by Joxit** [comment]
Hi there, new version out ! You can try the option `imagePullPolicy: Always` 

I pushed also some new tags: `2` and `2.0.x` as you requested :smile:

**Comment by Raboo** [comment]
Hi, no, it doesn't seem to restart or update automatically.. It's still running the old 2.0 image.
Perhaps it will update the tag if I kill the pod.

```yaml
  containerStatuses:
  - containerID: docker://57c82d5f387262ba3df91e2eef5b6b34fb46361bc9b585275b8a62da59e8a67f
    image: joxit/docker-registry-ui:2.0
    imageID: docker-pullable://joxit/docker-registry-ui@sha256:a7744142665d34baca0e3eb477eba93644c8e8a34663c2020edb1127d78dad54
    lastState: {}
    name: registry-ui
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-08-04T13:34:39Z"
```

**Comment by Joxit** [comment]
Yes, you must trigger a new deployement to see the update. This is not done automatically.

**Comment by Raboo** [comment]
(Sure, but that is still a very manual approach of managing an infrastructure, i.e. deleting the pod or similar.)

Anyway thank you for adding release as a tag in Docker Hub. I will switch from major to minor (i.e. joxit/docker-registry-ui:2.0 to 2.0.9). It makes it easier in my GitOps CI/CD pipeline and also later on I can use renovate bot to have automated pull requests that update my k8s yaml manifests.

**Comment by Joxit** [comment]
Happy to help :smile:
