### ISSUE TITLE
Image digest as a column

### ISSUE THREAD

**Issue by pkesso** [Joxit/docker-registry-ui#231]
**Is your feature request related to a problem? Please describe.**
It is impossible to copy image sha digest from 'hover'.

**Describe the solution you'd like**
It would be very useful to see sha digest of the tag in the tag list as a new column.

UPD: SHOW_CONTENT_DIGEST is not 'true' by default, as it was claimed, so it caused the problem. So SHOW_CONTENT_DIGEST=true must be specified explicitly.

**Comment by Joxit** [comment]
Hi and thank you for using my project :smile: 

The image digest column is already present, check this screenshot taken from v2.1.0
![image](https://user-images.githubusercontent.com/5153882/152638061-0713d5ea-e0e9-4468-af8b-e8e112ee029e.png)

I hide the content digest when the window is too small, but you can get the full `docker pull` command with the digest by clicking the copy button.

Since v2.0.0 the default value of `SHOW_CONTENT_DIGEST` is false, check the migration guide here https://github.com/Joxit/docker-registry-ui/wiki/Migrating-from-1.x-to-2.x

**Comment by Joxit** [comment]
Hi, I close this issue due to inactivity.
