### ISSUE TITLE
Make tag view left aligned

### ISSUE THREAD

**Issue by quotengrote** [Joxit/docker-registry-ui#297]
**Is your feature request related to a problem? Please describe.**

In my opinion the tag view should be aligned left. In its current state on wide monitors it looks a bit odd.

**Describe the solution you'd like**

I would like to see a option to set the aligntment to "left".

**Additional context**

![image](https://user-images.githubusercontent.com/38253905/234272992-3e3639be-000b-45e9-8690-64e53edf277b.png)

**Comment by Joxit** [comment]
Hi, thank you for using my project :smile: 

Yes you're right, this is a bit odd. This is mainly caused because the Content Digest is hidden. There is a lot op space that isn't filled... :confused: Checkout the [Live Demo with Content Digest activated](https://joxit.dev/docker-registry-ui/demo/#!/taglist/debian) 

In general we see numbers aligned to the right and other items to the left. So having this would be cool for you ?

| Creation Date | Size | Tag|History|D|
| :--- | ---: | :--- | :--- | :--- |
|5 days ago| 120 MB| very-long-tag-to-display|H|D|

The view will still be very empty though

**Comment by quotengrote** [comment]
Hi, and thank you for your project.

Yes, i did not see that parameter before, but that looks way better, thx.

**Comment by Joxit** [comment]
Okay, that's a good news :smile: I also aligned the Creation date to the left.
I didn't updated the tag because of the icon :sweat_smile:
