### ISSUE TITLE
[Feature] Hide empty repos

### ISSUE THREAD

**Issue by yourh3ro** [Joxit/docker-registry-ui#299]
When all tags are removed from the repository, it still continues to be displayed, which is misleading.
I suggest adding a setting to hide\display empty repositories.

**Comment by Joxit** [comment]
Hi, thank you for using my project and submitting feature requests.

In order to filter empty repositories, I have to, for each repositories, do a call to the API. This is already done when `SHOW_CATALOG_NB_TAGS` is activated.

What I can do is, when `SHOW_CATALOG_NB_TAGS` is true, I hide all empty repositories. Is it fine for you (instead of having a new option) ?

**Comment by yourh3ro** [comment]
In my case, it worked perfectly, but perhaps the project will lose flexibility. 
I myself cannot imagine a situation that someone needs to see that he has 0 tags in any section, but I do not exclude that people may have any processes that presuppose viewing empty repositories (for example, just for the sake of nostalgia, lol).

I want to say that this solution would suit me, but it's up to you to decide how to make it easier and more correct.

**Comment by Joxit** [comment]
Yes I know, this is a limitation of Docker Registry Server, the server should have deleted these images, but it doesn't work like that... See #77 

IMO adding this new option will duplicate with `SHOW_CATALOG_NB_TAGS`  since now it's supporting it now.

So it will be an option that will generate x new requests (the number of images) just like `SHOW_CATALOG_NB_TAGS` without the nice addition of `SHOW_CATALOG_NB_TAGS`.

So this addition is available in `main` tag for now :smile:
