### ISSUE TITLE
The information on how to run development environment is missing from the readme 

### ISSUE THREAD

**Issue by Vulwsztyn** [Joxit/docker-registry-ui#314]
Hi, I wanted to run the project locally. I did `npm i` and `npm start` and wanted to provide the link to my docker registry, but have no idea how as I am not familiar with rollup or riot. Could you provide information on how to run the dev environmant and how to change the projects variables

**Comment by Joxit** [comment]
Hi there, I've removed everything about how to run the dev mode since I don't have PR for the core of the project.
But yes this is pretty all, `npm install` and `npm start`, the missing part is the URL to access the UI which is http://localhost:8000/ :thinking:.
Oh and the second reason is `NGINX_*` configuration is not available in development mode.
