### ISSUE TITLE
HAProxy: Proxy infront of docker-registry-ui -> `unknown blob`

### ISSUE THREAD

**Issue by Zerka30** [Joxit/docker-registry-ui#331]
Hi :wave: ,

I have ran the following examples : https://github.com/Joxit/docker-registry-ui/tree/main/examples/ui-as-proxy

With following server configuration : 
curl registry.zerka.dev -> HAProxy -> Registry UI -> Registry

I can perfectly access to the web ui using username: `registry` & password: `ui`  

But I got some problem when pushing image to registry.

```
zerka@XPS-Zerka:~$ docker login https://registry.zerka.dev
Username: registry
Password: 
WARNING! Your password will be stored unencrypted in /home/zerka/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded

zerka@XPS-Zerka:~$ docker push registry.zerka.dev/mariadb
Using default tag: latest
The push refers to repository [registry.zerka.dev/mariadb]
979352cf408a: Pushing [==================================================>]  25.09kB
bd9845714e03: Pushing [==================================================>]  12.29kB
4f77fa6b63fd: Pushing [==================================================>]  310.6MB/310.6MB
4705f2253f14: Pushing [==================================================>]   5.12kB
79a67c5fcaf6: Pushing  2.048kB
a993cd96733e: Waiting 
9d45f71d173a: Waiting 
cdd7c7392317: Waiting 
unknown blob
```

This is a known issue ? How to solve this ?

**Comment by Joxit** [comment]
Hi, thank you for using my project and submitting issues :smile: 

Hum I need to locate where is the issue, if it's your HAProxy or the UI. I know I had to disable `proxy_buffering` and `proxy_request_buffering` to fix some issues on push...

So can you bypass the UI with your HAProxy and tell me if it works ?
```
curl registry.zerka.dev -> HAProxy -> Registry
```

**Comment by Joxit** [comment]
Hum okay, since this is probably caused by HAProxy and I'm not mastering it, I cannot help you with this issue...

I do not think that this is due to https, as I said with nginx I had to set some configurations in order to make the push over proxy work (`proxy_buffering` and `proxy_request_buffering`) 

https://github.com/Joxit/docker-registry-ui/blob/3414d7b5173fe6fd5d18f9bb3bc5522b3582cffd/nginx/default.conf#L15-L18

Could you do another test where you push via the UI ? I want to know if the UI configuration is really OK, if it's the case, you will need to find a way to copy nginx configuration to HAProxy. Can you send your registry logs too when you push your image?

```
curl local-ip -> Registry UI  -> Registry
```

I know that sometimes we cannot push heavy images
