### ISSUE TITLE
add possibility to delete a tag

### ISSUE THREAD

**Issue by FrancYescO** [Joxit/docker-registry-ui#392]
**Is your feature request related to a problem? Please describe.**
after deleting an image the tag will remain forever and there is no way to delete, neither garbage collector deletes it if there are no images under the tag

**Describe the solution you'd like**
add a button to delete a tag and all associated images, here a way on how that can be done via apis https://stackoverflow.com/a/71580038/5180992

also can be useful a button to call the garbage collector, but i assume there is no way to do via apis

**Comment by Joxit** [comment]
Hello, thank you for using my project and submitting issues.

Isn't the feature already available ? `DELETE_IMAGES` will delete the selected reference of the tag for a specific image.

Since the docker registry is working on references and layers, you must run the garbage collector manually to free your disk space.

![image](https://github.com/user-attachments/assets/66008f93-558f-4839-ade4-225582941a72)

**Comment by FrancYescO** [comment]
Hello as I said, the buttons will delete the tag but also after calling the garbage collector you will still find the image with no tags in (i.e. if you click all the bin buttons the UI will keep showing the page with no rows)

**Comment by Joxit** [comment]
Oh, yeah, so it's related to the FAQ question

> * Why, when I delete all tags of an image, the image is still in the UI ?
>   * This is a limitation of docker registry, the garbage collector don't remove empty images. If you want to delete dangling images, you will need to delete the folder in your registry data. (see https://github.com/Joxit/docker-registry-ui/issues/77)

Sorry, nothing can be done by the UI
