### ISSUE TITLE
sorting tags by date by default

### ISSUE THREAD

**Issue by greut** [Joxit/docker-registry-ui#45]
I've got many tags and they get sorted alphabetically by default. Could it be by date, the most recent first?

![screenshot from 2018-07-17 10-39-10](https://user-images.githubusercontent.com/1388/42806014-a8a492c2-89ad-11e8-9bc5-f4f03de64bb0.png)

Cheers,

**Comment by Joxit** [comment]
Hello,

If I do it in a smarter way, will that be fine? By finding the numbers among the tags and doing a numerical sort for example.

Retrieve creation dates will add more requests (because I will need [manifest schema v1](https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-1.md) and I use [manifests schema v2](https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md)) and will be hard to add in the user interface.

**Comment by greut** [comment]
@Joxit fair enough. Leave it be then. thanks!

**Comment by Joxit** [comment]
Added in 0.4.0; soon on docker hub :)
