### ISSUE TITLE
how can i custom the pull link ?

### ISSUE THREAD

**Issue by wuyue92tree** [Joxit/docker-registry-ui#71]
from: docker pull **192.168.1.29:4080**/drone-test:latest
to: docker pull **test.io**/drone-test:latest

Is there an option for this?

thanks~

**Comment by Joxit** [comment]
Hi,

What is the tag of the image you are using ?

**Comment by wuyue92tree** [comment]
> Hi,
> 
> What is the tag of the image you are using ?

like this   `192.168.1.29:5000/drone-test:latest`

**Comment by Joxit** [comment]
Sorry, I meant the image tag of `docker-registry-ui`.
The static version (like `docker-registry-ui:static`) or the default one (like `docker-registry-ui:latest`) ?

**Comment by wuyue92tree** [comment]
> Sorry, I meant the image tag of `docker-registry-ui`.
> The static version (like `docker-registry-ui:static`) or the default one (like `docker-registry-ui:latest`) ?
`docker-registry-ui:static`

**Comment by Joxit** [comment]
Okay, the environment variable `URL` is used to build the pull command, but this need some changes with the registry (CORS configuration).
And this will also by-pass the `REGISTRY_URL` environment variable and will not fit all use cases...
So I will add a new environment variable in order to customise the pull command and fit your needs :smile:.

**Comment by Joxit** [comment]
I did not mention the option, it's `PULL_URL`

**Comment by wuyue92tree** [comment]
> I did not mention the option, it's `PULL_URL`

It's cool. I'll try it, thanks a lot.

**Comment by Joxit** [comment]
You are welcome :smiley:
