### ISSUE TITLE
Mixed Content error

### ISSUE THREAD

**Issue by andreasschulze** [Joxit/docker-registry-ui#92]
Hello,

I already run a registry behind nginx. Registry listen on http://registry.example:5000 and don't require authentication. Authentication and HTTPS is handled by nginx. My registry is available as https://example.org, Nginx authenticate and serve https://example.org/v2/ via proxy_pass from http://registry.example:5000

Running a container "joxit/docker-registry-ui:static" runs an other nginx at the end of the day.
So I tried to
- use only the dist/ directory
- copied docker-registry-ui-static.js to docker-registry-ui.js
- sed -i "s,\${URL},http://registry.local:5000," docker-registry-ui.js
- sed -i "s,\${REGISTRY_TITLE},my Registry," docker-registry-ui.js

and let nginx serve /ui as alias to dist/

On access I receive a "Mixed Content error" ( https://github.com/Joxit/docker-registry-ui/blob/master/src/scripts/http.js#L93 )

Can I aviod / circumvent this?

Andreas

**Comment by Joxit** [comment]
Hello,

You can't avoid this error, [Mixed Content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#Mixed_active_content) is a browser security, you can't access http content on an https website (this is not the docker-registry-ui which trigger this error, I created an error mapping so that the error is more understandable).

When you use `sed -i "s,${URL},http://registry.local:5000," docker-registry-ui.js`, when you will access to the UI, your browser will do a request to `http://registry.local:5000`, if your UI is on an HTTPS site (`https://example.org/ui`) the request will be blocked, and that's normal. 

I think your issue here is how you use the URL of the registry. You are using a local URL, but you must use the external URL of your registry, that means `https://example.org`. Because your browser need to do a request on `https://example.org/v2/` and not `http://registry.local:5000/v2`.

So use : `sed -i "s,${URL},https://example.org," docker-registry-ui.js`

**Comment by andreasschulze** [comment]
I saw the UI more as proxy but now I understand, only the browser connects to both, UI and registry.

Thanks!

**Comment by Joxit** [comment]
Yes :)
To use the ui as a proxy, you will need docker and this example https://github.com/Joxit/docker-registry-ui/tree/master/examples/ui-as-proxy
